### ISSUE TITLE
engine error

### ISSUE THREAD

**Issue by steepexguys** [lewisclark/glua-steal#23]
when i join a server the game crash and it say engine error faild to lock vertex buffer 
![ff](https://user-images.githubusercontent.com/60797708/129483727-097306b9-0f31-4dda-abeb-526944db06a5.png)
?

**Comment by lewisclark** [comment]
Fairly certain this isn't an issue with glua-steal. I've had this countless times without using glua-steal on certain servers and it's been reported multiple times in the gmod community, too.
