### ISSUE TITLE
Lua script gets executed many times?

### ISSUE THREAD

**Issue by unixquuw** [lewisclark/glua-steal#25]
Basically, gluasteal executes the same lua script more than 1 time.

**Comment by lewisclark** [comment]
https://github.com/lewisclark/glua-steal/issues/20#issuecomment-708134163

**Comment by unixquuw** [comment]
> [#20 (comment)](https://github.com/lewisclark/glua-steal/issues/20#issuecomment-708134163)

thanks <3
