### ISSUE TITLE
Lua being appended.

### ISSUE THREAD

**Issue by wrefgtzweve** [lewisclark/glua-steal#35]
**Describe the bug**
If you join a server of whose files you already have it appends it to the file. This leads to a lot of double code in files and makes it painful to easily search through lua / files.

Preferably there would be an option to overwrite the file or make a new one with a new name, or even add a date per server folder so you can have multiple copies of the same server.

**Additional details (please complete the following information):**
64bit v1.9

**Comment by lewisclark** [comment]
Lua code is appended to prevent servers from overwriting Lua files using RunString and thus hiding their code: https://github.com/darkjacky/pwnscripthook/blob/e9932f7c83f5bae4b95c8d72c743f6348e6445ea/lua/autorun/client/cl_scripthookpwnd.lua#L17-L26. I'll definitely add an option in the config to choose between appending and overwriting, though.

**Comment by lewisclark** [comment]
Added in v2.0 - thanks for the issue.
