### ISSUE TITLE
How do I use this when a server is running gluapack

### ISSUE THREAD

**Issue by Skemiil** [lewisclark/glua-steal#40]
I only get the titles of the addon, every single lua file looks like this https://i.imgur.com/iUmW46i.png this isn't a issue with the tool itself but if anyone knows how to resolve this please help.

**Comment by x4fx77x4f** [comment]
When gluapack is in use, the actual code is contained inside BSP files. Check `garrysmod/download/data/gluapack/`.
Not sure how you would actually go about extracting the code from it though. I would investigate it myself, but I'm IP banned from gluapack's CDN. (Don't ask why because I don't know.)

**Comment by wrefgtzweve** [comment]
Just curious and a bit off topic here, but im going to ask anyways. What happens when you're banned from the CDN? does the server just not give you any lua and does nothing work for you?

**Comment by lewisclark** [comment]
Closing due to having no plans of implementing this in glua-steal. There are BSP parsers written in Lua for Garry's Mod and lots of documentation surrounding the BSP format if you wish to tackle this.
