### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by BazZziliuS** [lewisclark/glua-steal#46]
Can I cancel this or that code that is being executed on me?
For example, screengrab or crash attempt

Something like that
```
	if b:find("while true do end") then
	    return
	end

```

**Comment by lewisclark** [comment]
Yep.

```lua
if gluasteal.SOURCE:find("while true do end") then
    return false
end
```

**Comment by BazZziliuS** [comment]
> Yep.
> 
> ```lua
> if gluasteal.SOURCE:find("while true do end") then
>     return false
> end
> ```

Even without a hook?

**Comment by lewisclark** [comment]
> > Yep.
> > ```lua
> > if gluasteal.SOURCE:find("while true do end") then
> >     return false
> > end
> > ```
> 
> Even without a hook?

You don't need a hook to prevent `while true do end` from being executed on the client. Bear in mind that this is not a good way to prevent this sort of thing, though.

You *would* need some form of hook to prevent screen captures.
