### ISSUE TITLE
Gluasteal adding extra newlines to stolen files.

### ISSUE THREAD

**Issue by wrefgtzweve** [lewisclark/glua-steal#47]
Gluasteal seems to be adding excessive amounts to all stolen files, this happens for every server i've been on so far.

Downloaded file:
![image](https://user-images.githubusercontent.com/69946827/203663839-e6ec19d0-ca1c-4d3d-be6d-3f5dd810c6c5.png)

Original file:
https://github.com/Facepunch/garrysmod/blob/master/garrysmod/gamemodes/sandbox/gamemode/cl_notice.lua

Using 64x windows v2.0

**Comment by lewisclark** [comment]
Probably something to do with \r\n (0x0d 0x0a) being translated to \n\n (0x0a 0x0a). I've pushed some changes that might fix the issue - could you try it and let me know how it goes.

You can download the DLL from https://github.com/lewisclark/glua-steal/actions/runs/3540704254 if you're not building from source.

**Comment by wrefgtzweve** [comment]
Yeah that worked, looks just like the original one. Thanks!
![image](https://user-images.githubusercontent.com/69946827/203812847-c44c85ec-7770-40e1-b3ea-7bde31f94da5.png)

**Comment by lewisclark** [comment]
Awesome, thanks.
