### ISSUE TITLE
i need a tut on yt

### ISSUE THREAD

**Issue by dasd46785** [lewisclark/glua-steal#51]
hello i am new and i need a tut on yt because i dont get it

**Comment by shockpast** [comment]
## Requirements
- (32/64)-bit system, x64 is most recommended
- DLL Injector such as Process Hacker (not nightly) or Extreme Injector (Anti-Virus will be angry about this one)

## Steps to Use
1. [Download](https://github.com/lewisclark/glua-steal/releases/download/v2.1/gluasteal-v2.1-64bit.dll)
2. Place DLL on your Desktop or somewhere that is good for you
3. Process Hacker
3.1. (If your's GMod is 64bit, then find "gmod.exe", else "hl2.exe")
3.2. RMB (Right Click) at (gmod.exe/hl2.exe) and select Miscellaneous
3.3. LMB (Left Click) at "Inject DLL..." and select `gluasteal-v%.%-%bit.dll`
4. Garry's Mod might be still running, so you will need to try joining some servers and then checking folder "Documents/gluasteal/servers/"
5. fin

## Uhh...
folders in `Documents/gluasteal/servers/` will be named as IP:PORT
i can't do video, so i hope i wrote this pretty good

**Comment by maplepy** [comment]
What about for Linux @shockpast ?

**Comment by shockpast** [comment]
> What about for Linux @shockpast ?

idk

**Comment by lewisclark** [comment]
> hello i am new and i need a tut on yt because i dont get it

Be specific? What don't you get? Have you looked at the readme?

> What about for Linux @shockpast ?

There are instructions on how to build and use glua-steal on Linux in the readme.

**Comment by maplepy** [comment]
> The instructions

```
Recommended: [gdb](https://github.com/AimTuxOfficial/AimTux/blob/master/load)
    [linux-inject](https://github.com/gaffe23/linux-inject)
    using [LD_PRELOAD](https://man7.org/linux/man-pages/man8/ld.so.8.html), e.g. by modifying the Garry's Mod launch script (hl2.sh)
```

**Comment by lewisclark** [comment]
> > The instructions
> 
> ```
> Recommended: [gdb](https://github.com/AimTuxOfficial/AimTux/blob/master/load)
>     [linux-inject](https://github.com/gaffe23/linux-inject)
>     using [LD_PRELOAD](https://man7.org/linux/man-pages/man8/ld.so.8.html), e.g. by modifying the Garry's Mod launch script (hl2.sh)
> ```
> 
> Im not too sure how to inject it tbh, I have tried linux inject and gdb but none of those seems to work

gdb injection works great for me and others - here's a script you can use: https://github.com/lewisclark/glua-steal/issues/21#issuecomment-876401038

**Comment by maplepy** [comment]
> here's a script you can use: [#21 (comment)](https://github.com/lewisclark/glua-steal/issues/21#issuecomment-876401038)

I think I used it correctly, 

1. used the built .so file from glua steal, 
2. setup my .lua file to run in the toml file at first then tried in the include section of the "default" lua file
3. got the pid from the `top` command and looked at `gmod.exe`
4. used the script with `(pid from top) (.so file)`
5. nothing happened

**Comment by maplepy** [comment]
either I built the .so wrong, or my glua steal folder is fucked or somethign

**Comment by lewisclark** [comment]
Are you matching the build instructions with the version of the game you are running (32 bit or 64 bit)? You also must specify the full path to the library file, not a relative one.

**Comment by maplepy** [comment]
Ooh maybe thats why, I was using the relative path!

When do you inject it and how do you check the pid and version (32 or 64) of the executable? I'm not sure which version it is (should be Chromium 64, but there is a way to start it in 32) ? 

Other than that, do you recon I'm doing something from my instructions?

**Comment by lewisclark** [comment]
Inject at the main menu when you first launch the game. By default, Garry's Mod is installed as a 32-bit program. You can change it to 64-bit in Steam by going to the 'Betas' section under Garry's Mod. You 100% must use an absolute path when using that script, so hopefully that is your issue.

**Comment by maplepy** [comment]
Thank you very much! I will try when I come home from work then and let you know :) 

For some reason my Gmod was in the "_normal_" mode but a server asked for the `Chromium x64 binaries` version so I switched to it but now whenever I try to join a server on any version but Chromium my game crash so I must be in `Chromium x64 binaries`

**Comment by maplepy** [comment]
So you know, I used your script with the full path, tried with both 32bits and 64bits version and none of those worked

**Comment by maplepy** [comment]
Just tried with linux-inject and got this 
`./inject -p $(pgrep hl2) /home/maplepy/Github/gmod/gluasteal.so`
```
targeting process with pid 58251
ptrace(PTRACE_POKETEXT) failed
```

**Comment by maplepy** [comment]
![image](https://user-images.githubusercontent.com/28269333/211651764-d4be5e04-6726-4540-bdef-e0977db36a17.png)
this is the version i'm running

please answers those so I know what's wrong:

1. are you using proton or the native version?
2. what version of gmod are you running?
3. did you compile in 64 or 32?

or maybe try to send me your .so file so I can check if my build is wrong?
thank you very much

**Comment by lewisclark** [comment]
Strange. I've just tested both 32-bit and 64-bit with no issues. Native only - I wouldn't recommend using Proton.

> did you compile in 64 or 32?

You must compile to match the architecture of Garry's Mod. 64-bit -> 64-bit and 32-bit -> 32-bit.

You can download precompiled from the bottom of [this page](https://github.com/lewisclark/glua-steal/actions/runs/3776135583).

**Comment by maplepy** [comment]
Well I might be missing something because even with those it seems like it does not work

`~/Github/gmod ❯ ./gdb_inject.sh 56047 /home/maplepy/Github/gmod/binaries/gluasteal-ubuntu-20.04-gcc9-gcc-32bit-Release.so`
```
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Successfully injected
```!

`~/Github/gmod ❯ ./gdb_inject.sh 56047 /home/maplepy/Github/gmod/binaries/gluasteal-ubuntu-22.04-gcc11-gcc-32bit-Release.so`
```
warning: Could not load shared library symbols for bin/launcher.so.
Do you need "set solib-search-path" or "set sysroot"?
Successfully injected!
```

**Comment by maplepy** [comment]
I just managed to fix it !! Thank you so much for the help and for trying for so long to help me bro!

The fix: basically I tried with both the gcc9 and gcc11 and tried every 3 of those pid, eventually one worked and it seems like it created the gluasteal folder and every file associated with it

**Comment by maplepy** [comment]
I'm just note sure how to run my .lua files now? Should they be in the config.toml or in the gluasteal.lua or somewhere else?

**Comment by lewisclark** [comment]
Great! The default file is `gluasteal.lua` but can be changed in the config file.

**Comment by maplepy** [comment]
What would be the best way to run a menu when i spawned in the server? because as of now it doesnt seem to load when im connected

**Comment by lewisclark** [comment]
Something like this will execute your file once the base Lua files have loaded:

gluasteal.lua
```lua
if gluasteal.SCRIPT == "includes/extensions/client/render.lua" then
    gluasteal.include("loaded.lua")
end
```

loaded.lua
```lua
-- your code here
```

**Comment by lewisclark** [comment]
Yes, it would load `loaded.lua` once, right before `render.lua` is loaded.
