### ISSUE TITLE
The sv_lua file is not downloaded.

### ISSUE THREAD

**Issue by HashBlobb** [lewisclark/glua-steal#52]
How do I download the sv_lua(sv_hooks.lua, sv_schema) file?

**Comment by lewisclark** [comment]
> gluasteal retrieves **client-side & shared** Lua files from Garry's Mod servers that you join. gluasteal also allows you to execute your own Lua code on any server.

Files beginning with `sv_` are usually server-side files. Garry's Mod does not network these to the client, therefore they cannot be retrieved.
