### ISSUE TITLE
lldb is failing to inject

### ISSUE THREAD

**Issue by StupidRepo** [lewisclark/glua-steal#56]
<img width="574" alt="image" src="https://user-images.githubusercontent.com/69256931/227784413-68416843-3741-4eb3-ae3b-f032bab91efd.png">
It keeps quitting Garry's Mod.

**Comment by StupidRepo** [comment]
@lewisclark This happens randomly and it happens a lot so I created a [little helper script](https://github.com/lewisclark/glua-steal/files/11072671/gmodhax.zip) which uses bash. Basically, you run the script and then launch Garry's Mod then it'll hack it. The game may crash and if that happens then it'll keep trying until it works (so there is no need to start the script each time it crashes).

I hope there will be a fix for the constant crashing in the future!

Oh and, make sure to change the libgluasteal path in the script to the location of libgluasteal.dylib/whatever the file type for gluasteal is for Linux.

**Comment by lewisclark** [comment]
> @lewisclark This happens randomly and it happens a lot so I created a [little helper script](https://github.com/lewisclark/glua-steal/files/11072671/gmodhax.zip) which uses bash. Basically, you run the script and then launch Garry's Mod then it'll hack it. The game may crash and if that happens then it'll keep trying until it works (so there is no need to start the script each time it crashes).
> 
> I hope there will be a fix for the constant crashing in the future!
> 
> Oh and, make sure to change the libgluasteal path in the script to the location of libgluasteal.dylib/whatever the file type for gluasteal is for Linux.

Nice. Any further info/logs would be appreciated if you have any, because I don't have a macOS virtual machine at hand atm.

**Comment by StupidRepo** [comment]
I don't have any other logs unfortunately, but if you do end up finding a
fix to this that'd be greatly appreciated.
