### ISSUE TITLE
Is Overriding Lua Files Possible?

### ISSUE THREAD

**Issue by NobleFalcon** [lewisclark/glua-steal#60]
I'm interested in knowing whether it's possible to override existing Lua files while maintaining full access to the source file's methods and networking. I need to alter the behavior of the existing lua file without losing their inherent network communication abilities and method implementations.

For example `net.ReadUInt(16)` or `local obj = OBJ.RANK` will no longer be accessible if I use:
```lua
if (gluasteal.SCRIPT:match("cl_ranks")) then
    gluasteal.include("cl_ranks.lua")
    return false
end
```

**Comment by lewisclark** [comment]
You can store the contents of a file at execution time using the `gluasteal.SOURCE` variable - from there you can programmatically pull out the code you require and execute it using `RunString`. I would prefer to achieve the desired result by overriding global functions it calls or copying all code required into a new replacement file to be executed instead.
