### ISSUE TITLE
gluasteal not working

### ISSUE THREAD

**Issue by qu1nity** [lewisclark/glua-steal#62]
gluasteal not working on linux(ubuntu64), im compiled the file and inject into gmod 64bit and gmod 32bit, but, inject succeful, like nothing just happens. I recompiled the sources several times, used different injectors, but still nothing happens, the last time I used this was the GDB method, does not work stealer and lua executor. The directory is not created.

**Comment by lewisclark** [comment]
What does GDB return after injecting? Are you 100% sure of the libgluasteal.so path you are giving it? Things are working fine on my end on Linux, so I imagine it to be an injection issue on your end.

**Comment by qu1nity** [comment]
> What does GDB return after injecting? Are you 100% sure of the libgluasteal.so path you are giving it? Things are working fine on my end on Linux, so I imagine it to be an injection issue on your end.

output by GDB: 0x0, and yes im giving full path to .so file

**Comment by qu1nity** [comment]
Here is the detailed input and output in GDB:
![image](https://github.com/lewisclark/glua-steal/assets/170981154/c6d18e2b-f202-46c7-9595-23a5c7ee25bd)

**Comment by qu1nity** [comment]
On my system, working GDB only, with linux-inject he writes about segmentation fault, and gluasteal folder i created

**Comment by lewisclark** [comment]
Strange - in GDB, can you call [dlerror](https://linux.die.net/man/3/dlerror) after calling dlopen? It should return a string describing the error. 

edit: looks like the issue might be related to glibc linking? dlerror should confirm

**Comment by qu1nity** [comment]
how write this string after calling dlopen, i basically don’t know very well how everything works in linux

**Comment by lewisclark** [comment]
> how write this string after calling dlopen, i basically don’t know very well how everything works in linux

I haven't tested but this should work in GDB:
```
set $dlerror = (char*(*)()) dlerror
call $dlerror()
```

**Comment by qu1nity** [comment]
elfclass64
![image](https://github.com/lewisclark/glua-steal/assets/170981154/2d41db78-7d0e-4b30-bed6-45a3d725b396)

**Comment by lewisclark** [comment]
> elfclass64 ![image](https://private-user-images.githubusercontent.com/170981154/335344202-2d41db78-7d0e-4b30-bed6-45a3d725b396.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTcwOTUzMDEsIm5iZiI6MTcxNzA5NTAwMSwicGF0aCI6Ii8xNzA5ODExNTQvMzM1MzQ0MjAyLTJkNDFkYjc4LTdkMGUtNGIzMC1iZWQ2LTQ1YTNkNzI1YjM5Ni5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTMwJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUzMFQxODUwMDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jY2U1ZTljZjM4Y2RmMTkyYjk2ZDNjM2Y1MjI3NjhhM2NmMWFiNGQyNjU5MDllMDc0NjkzMmM2ZmY5MjMyMDcxJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.CKz211GBhBmL3qK6I-iCx4QyFPBdKaeL7GMGuYpYxKk)

It looks like you're trying to inject the 64-bit library into 32-bit Garry's Mod. You should either compile the library in 32-bit mode or [use the Garry's Mod 64-bit beta](https://steamcommunity.com/sharedfiles/filedetails/?id=2725447709)

**Comment by qu1nity** [comment]
yea, glibc needed
![image](https://github.com/lewisclark/glua-steal/assets/170981154/4baba1e4-a854-4a4d-bb74-10de9ea9db59)

**Comment by qu1nity** [comment]
i fuck this shit, im installed all lib, but, the error did not go away

**Comment by lewisclark** [comment]
It looks like a conflict with the Steam runtime, it provides its own version of glibc which is a few versions lower than the native version of glibc used to link with gluasteal. 

The options are either:
- Disable the Steam runtime using `STEAM_RUNTIME=0` environment variable and resort to native libraries
- Compile gluasteal with a lower glibc version
- Make Steam link to a newer glibc version (2.39)

**Comment by qu1nity** [comment]
Thx, its work
